---

include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

language: android

jdk:
  - oraclejdk8

sudo: required

addons:
  apt:
    packages:
      - oracle-java8-installer

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - tools # TODO force travis to fetch latest tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-30.0.2

    # The SDK version used to compile your project
    - android-31
  licenses:
    - 'android-sdk-license-.+'

before_install:
  - yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || if [ $? -ne '141' ]; then exit $?; fi;  #Captures SIGPIPE 141 error but still allow repeating "y" to accept all licenses

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache/

sast:
  stage: check

script:
  - '.travis/${TASK}.sh'

env:
  - TASK=lint
  - TASK=test

after_success:
  - .travis/coverage.sh
