---

name: Gradle Check Versions

on:
  schedule:
  - cron: '0 0 * * 0'
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
    name: Java ${{ matrix.java }}
    steps:
    - name: Set REPOSITORY
      run: echo "REPOSITORY=${GITHUB_REPOSITORY#*/}" >> "${GITHUB_ENV}"
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - name: Check versions
      run: ./gradlew --refresh-dependencies dependencyUpdates
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.REPOSITORY }}
        path: |
          build/dependencyUpdates/
          app/build/dependencyUpdates/
