---
# This is a basic workflow to help you get started with Actions

name: Gradle

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
    name: Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: android-nfc-timestamp
        path: |
          app/build/outputs/
          app/build/reports/
